SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' ORDER BY apellido1 ASC, apellido2 ASC, nombre ASC;
SELECT * FROM persona WHERE tipo = 'alumno' AND telefono IS NULL;
SELECT * FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento BETWEEN '1999-01-01' AND '2000-01-01';
SELECT * FROM persona WHERE tipo = 'profesor' AND telefono IS NULL AND nif REGEXP 'K$';
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT pe.apellido1, pe.apellido2, pe.nombre, pr.id_departamento FROM persona pe JOIN profesor pr ON pr.id_departamento = pe.id JOIN departamento ON departamento.id = pr.id_departamento WHERE tipo = 'profesor' ORDER BY apellido1 ASC, apellido2 ASC, nombre ASC;
SELECT a.nombre, c.anyo_inicio, anyo_fin FROM alumno_se_matricula_asignatura ma JOIN asignatura a ON ma.id_asignatura = a.id JOIN curso_escolar c ON c.id = ma.id_curso_escolar JOIN persona p ON p.id = ma.id_alumno WHERE nif = '26902806M';
SELECT d.nombre FROM asignatura a JOIN profesor pr ON a.id_profesor = pr.id_profesor JOIN departamento d ON pr.id_departamento = d.id WHERE id_grado = (SELECT id FROM grado WHERE nombre = 'Grado en Ingeniería Informática (Plan 2015)');
SELECT p.apellido1, p.apellido2, p.nombre FROM alumno_se_matricula_asignatura am JOIN persona p	ON p.id = am.id_alumno WHERE p.tipo = 'alumno' AND am.id_curso_escolar = (SELECT id FROM curso_escolar WHERE anyo_inicio = '2018') GROUP BY am.id_alumno;
SELECT d.nombre AS 'departamento', apellido1, apellido2, p.nombre FROM profesor pr RIGHT JOIN  persona p ON pr.id_profesor = p.id LEFT JOIN departamento d ON pr.id_departamento = d.id ORDER BY departamento, apellido1, apellido2, nombre;
SELECT d.nombre AS 'departamento', apellido1, apellido2, p.nombre FROM profesor pr RIGHT JOIN  persona p ON pr.id_profesor = p.id LEFT JOIN departamento d ON pr.id_departamento = d.id WHERE d.nombre IS NULL;
SELECT d.nombre AS 'departamento' FROM profesor pr LEFT JOIN persona p ON pr.id_profesor = p.id RIGHT JOIN departamento d ON pr.id_departamento = d.id WHERE p.nombre IS NULL;
SELECT pr.id_profesor FROM profesor pr LEFT JOIN asignatura a ON pr.id_profesor = a.id_profesor LEFT JOIN persona p ON pr.id_profesor = p.id WHERE a.nombre IS NULL;
SELECT a.nombre FROM profesor pr RIGHT JOIN asignatura a ON pr.id_profesor = a.id_profesor LEFT JOIN persona p ON pr.id_profesor = p.id WHERE a.id_profesor IS NULL;
SELECT d.id, d.nombre FROM departamento d LEFT JOIN profesor pr ON d.id = pr.id_departamento LEFT JOIN asignatura ag ON pr.id_profesor = ag.id_profesor LEFT JOIN curso_escolar c ON ag.curso = c.id WHERE c.anyo_inicio IS NULL GROUP BY d.id;
SELECT count(id) FROM persona WHERE tipo = 'alumno';
SELECT count(id) FROM persona WHERE fecha_nacimiento BETWEEN '1999-01-01' AND '2000-01-01' AND tipo = 'alumno';
SELECT d.nombre, count(pr.id_profesor) FROM departamento d JOIN profesor pr ON d.id = pr.id_departamento GROUP BY d.nombre;
SELECT d.nombre, count(pr.id_profesor) FROM departamento d LEFT JOIN profesor pr ON d.id = pr.id_departamento GROUP BY d.nombre;
SELECT g.nombre, count(ag.id) AS count FROM grado g LEFT JOIN asignatura ag ON g.id = ag.id_grado GROUP BY g.nombre ORDER BY count DESC;
SELECT grado.nombre, COUNT(asignatura.id_grado) AS numero_asignaturas FROM grado LEFT JOIN asignatura ON asignatura.id_grado = grado.id GROUP BY grado.nombre HAVING numero_asignaturas > 40 ORDER BY numero_asignaturas DESC;
SELECT grado.nombre, asignatura.tipo, SUM(asignatura.creditos) FROM grado JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.nombre, asignatura.tipo, asignatura.creditos;
SELECT curso_escolar.anyo_inicio, COUNT(persona.nombre) FROM alumno_se_matricula_asignatura JOIN persona ON persona.id = alumno_se_matricula_asignatura.id_alumno JOIN curso_escolar ON curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar GROUP BY curso_escolar.anyo_inicio;
SELECT profesor.id_profesor, persona.nombre, persona.apellido1, persona.apellido2, COUNT(asignatura.nombre) AS numero_de_asignaturas FROM profesor LEFT JOIN asignatura ON asignatura.id_profesor = profesor.id_profesor JOIN persona ON persona.id = profesor.id_profesor GROUP BY profesor.id_profesor ORDER BY numero_de_asignaturas DESC;
SELECT * FROM persona ORDER BY fecha_nacimiento DESC LIMIT 1;
SELECT persona.nombre, persona.apellido1, persona.apellido2, persona.id AS id_profesor, departamento.id AS id_departamento FROM departamento JOIN profesor ON profesor.id_departamento = departamento.id LEFT JOIN asignatura ON asignatura.id_profesor = profesor.id_profesor JOIN persona ON persona.id = profesor.id_profesor WHERE asignatura.nombre IS NULL;